#############################################################################
# Makefile for building: Demo
# Generated by qmake (2.01a) (Qt 4.7.3) on: Thu Mar 3 15:08:34 2016
# Project:  Demo.pro
# Template: app
# Command: /home/alianpaul/qt/qt-everywhere-opensource-src-4.7.3/qt/bin/qmake -o Makefile Demo.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-none-linux-gnueabi-gcc
CXX           = arm-none-linux-gnueabi-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/qws/linux-arm-gnueabi-g++ -I. -I../../qt/qt-everywhere-opensource-src-4.7.3/qt/include/QtCore -I../../qt/qt-everywhere-opensource-src-4.7.3/qt/include/QtNetwork -I../../qt/qt-everywhere-opensource-src-4.7.3/qt/include/QtGui -I../../qt/qt-everywhere-opensource-src-4.7.3/qt/include -I. -Ikeyboard -I. -I.
LINK          = arm-none-linux-gnueabi-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/alianpaul/qt/qt-everywhere-opensource-src-4.7.3/qt/lib
LIBS          = $(SUBLIBS)  -L/home/alianpaul/qt/qt-everywhere-opensource-src-4.7.3/qt/lib -lQtGui -L/home/alianpaul/qt/qt-everywhere-opensource-src-4.7.3/qt/lib -lQtNetwork -lQtCore -lpthread 
AR            = arm-none-linux-gnueabi-ar cqs
RANLIB        = 
QMAKE         = /home/alianpaul/qt/qt-everywhere-opensource-src-4.7.3/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-none-linux-gnueabi-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ipconfigdialog.cpp \
		main.cpp \
		maindialog.cpp \
		utility.cpp \
		keyboard.cpp moc_ipconfigdialog.cpp \
		moc_maindialog.cpp \
		moc_keyboard.cpp
OBJECTS       = ipconfigdialog.o \
		main.o \
		maindialog.o \
		utility.o \
		keyboard.o \
		moc_ipconfigdialog.o \
		moc_maindialog.o \
		moc_keyboard.o
DIST          = ../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/g++.conf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/unix.conf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/linux.conf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/qws.conf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/qconfig.pri \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/modules/qt_webkit_version.pri \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/qt_functions.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/qt_config.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/exclusive_builds.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/default_pre.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/release.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/default_post.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/warn_on.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/qt.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/unix/thread.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/moc.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/resources.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/uic.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/yacc.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/lex.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/include_source_dir.prf \
		Demo.pro
QMAKE_TARGET  = Demo
DESTDIR       = 
TARGET        = Demo

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_ipconfigdialog.h ui_maindialog.h ui_keyboard.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Demo.pro  ../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/qws/linux-arm-gnueabi-g++/qmake.conf ../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/g++.conf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/unix.conf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/linux.conf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/qws.conf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/qconfig.pri \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/modules/qt_webkit_version.pri \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/qt_functions.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/qt_config.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/exclusive_builds.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/default_pre.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/release.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/default_post.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/warn_on.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/qt.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/unix/thread.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/moc.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/resources.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/uic.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/yacc.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/lex.prf \
		../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/include_source_dir.prf \
		/home/alianpaul/qt/qt-everywhere-opensource-src-4.7.3/qt/lib/libQtGui.prl \
		/home/alianpaul/qt/qt-everywhere-opensource-src-4.7.3/qt/lib/libQtNetwork.prl \
		/home/alianpaul/qt/qt-everywhere-opensource-src-4.7.3/qt/lib/libQtCore.prl
	$(QMAKE) -o Makefile Demo.pro
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/g++.conf:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/unix.conf:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/linux.conf:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/qws.conf:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/qconfig.pri:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/modules/qt_webkit_version.pri:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/qt_functions.prf:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/qt_config.prf:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/exclusive_builds.prf:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/default_pre.prf:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/release.prf:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/default_post.prf:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/warn_on.prf:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/qt.prf:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/unix/thread.prf:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/moc.prf:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/resources.prf:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/uic.prf:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/yacc.prf:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/lex.prf:
../../qt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/include_source_dir.prf:
/home/alianpaul/qt/qt-everywhere-opensource-src-4.7.3/qt/lib/libQtGui.prl:
/home/alianpaul/qt/qt-everywhere-opensource-src-4.7.3/qt/lib/libQtNetwork.prl:
/home/alianpaul/qt/qt-everywhere-opensource-src-4.7.3/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Demo.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Demo1.0.0 || $(MKDIR) .tmp/Demo1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Demo1.0.0/ && $(COPY_FILE) --parents ipconfigdialog.h maindialog.h utility.h keyboard.h .tmp/Demo1.0.0/ && $(COPY_FILE) --parents ipconfigdialog.cpp main.cpp maindialog.cpp utility.cpp keyboard.cpp .tmp/Demo1.0.0/ && $(COPY_FILE) --parents ipconfigdialog.ui maindialog.ui keyboard.ui .tmp/Demo1.0.0/ && (cd `dirname .tmp/Demo1.0.0` && $(TAR) Demo1.0.0.tar Demo1.0.0 && $(COMPRESS) Demo1.0.0.tar) && $(MOVE) `dirname .tmp/Demo1.0.0`/Demo1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Demo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ipconfigdialog.cpp moc_maindialog.cpp moc_keyboard.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ipconfigdialog.cpp moc_maindialog.cpp moc_keyboard.cpp
moc_ipconfigdialog.cpp: ipconfigdialog.h
	/home/alianpaul/qt/qt-everywhere-opensource-src-4.7.3/qt/bin/moc $(DEFINES) $(INCPATH) ipconfigdialog.h -o moc_ipconfigdialog.cpp

moc_maindialog.cpp: maindialog.h
	/home/alianpaul/qt/qt-everywhere-opensource-src-4.7.3/qt/bin/moc $(DEFINES) $(INCPATH) maindialog.h -o moc_maindialog.cpp

moc_keyboard.cpp: keyboard.h
	/home/alianpaul/qt/qt-everywhere-opensource-src-4.7.3/qt/bin/moc $(DEFINES) $(INCPATH) keyboard.h -o moc_keyboard.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_ipconfigdialog.h ui_maindialog.h ui_keyboard.h
compiler_uic_clean:
	-$(DEL_FILE) ui_ipconfigdialog.h ui_maindialog.h ui_keyboard.h
ui_ipconfigdialog.h: ipconfigdialog.ui
	/home/alianpaul/qt/qt-everywhere-opensource-src-4.7.3/qt/bin/uic ipconfigdialog.ui -o ui_ipconfigdialog.h

ui_maindialog.h: maindialog.ui
	/home/alianpaul/qt/qt-everywhere-opensource-src-4.7.3/qt/bin/uic maindialog.ui -o ui_maindialog.h

ui_keyboard.h: keyboard.ui
	/home/alianpaul/qt/qt-everywhere-opensource-src-4.7.3/qt/bin/uic keyboard.ui -o ui_keyboard.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

ipconfigdialog.o: ipconfigdialog.cpp ipconfigdialog.h \
		ui_ipconfigdialog.h \
		utility.h \
		keyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ipconfigdialog.o ipconfigdialog.cpp

main.o: main.cpp maindialog.h \
		ipconfigdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

maindialog.o: maindialog.cpp maindialog.h \
		ui_maindialog.h \
		ipconfigdialog.h \
		utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maindialog.o maindialog.cpp

utility.o: utility.cpp utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utility.o utility.cpp

keyboard.o: keyboard.cpp keyboard.h \
		ui_keyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keyboard.o keyboard.cpp

moc_ipconfigdialog.o: moc_ipconfigdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ipconfigdialog.o moc_ipconfigdialog.cpp

moc_maindialog.o: moc_maindialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_maindialog.o moc_maindialog.cpp

moc_keyboard.o: moc_keyboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_keyboard.o moc_keyboard.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

